import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased max-w-[1440px] mx-auto`}
      >
        <Header />
        <main className="min-h-[100vh]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
